### ISSUE TITLE
Appears to be broken in 1.16.3

### ISSUE THREAD

**Issue by deversmann** [MadCatHoG/OnePlayerSleepV4-Data-Pack#1]
Shows as "Incompatible (Made for an older version of Minecraft)"

**Comment by dhouck** [comment]
It should still be completely compatible I think; just the version in pack.mcmeta should be 6 instead of 5.

**Comment by MadCatHoG** [comment]
that is correct, the pack version might make it seem incompatible but it should still work. A recent update for Minecraft 1.20+ should address that for the current version.
