### ISSUE TITLE
Fast-forwarding might trigger zombie siege

### ISSUE THREAD

**Issue by dhouck** [MadCatHoG/OnePlayerSleepV4-Data-Pack#2]
Zombie sieges can happen with a 10% chance when players are near a large enough village at precisely midnight.  If all players are asleep, then "precisely midnight" cannot happen, but if only one player is asleep with this pack then it will happen one in 41 nights, for a chance of 1/410 of a zombie siege.

That isn't much, but it's still more than ideal; if possible the pack should deliberately make sure the tick at midnight doesn't happen if anyone's asleep.

**Comment by MadCatHoG** [comment]
I've never thought of this in the past, though this is something that server administrators should choose to avoid if their players want it, here is how you can do it:
Change this [file](https://github.com/MadCatHoG/OnePlayerSleepV4-Data-Pack/blob/5b4bd22a82ea7e655860c543bd16a2d4cb020dfa/data/ops/functions/main.mcfunction#L20C54-L20C54), line 20. The number at the end could be an odd number like 43, and that will reduce the chance of hitting exactly midnight.
